### ISSUE TITLE
Feature: add Apple Silicon support

### ISSUE THREAD

**Issue by Shchvova** [keeshux/openssl-apple#21]
potentially related to
openssl/openssl#12254

**Comment by adib** [comment]
@keeshux I've added Apple Silicon support in [a downstream repo](https://github.com/balthisar/openssl-xcframeworks/pull/6). There is not much recent activity in that repo though, so I'm not really sure where this PR should go.

**Comment by keeshux** [comment]
> @keeshux I've added Apple Silicon support in [a downstream repo](https://github.com/balthisar/openssl-xcframeworks/pull/6). There is not much recent activity in that repo though, so I'm not really sure where this PR should go.

Thanks for the info, I'm trying to backport those changes into this repository. Any particular reason why you guys forked _that_ much instead of considering PRs? Anything else beyond XCFrameworks?

**Comment by adib** [comment]
@keeshux Me? I was looking for an OpenSSL distribution that supports iOS, Simulator, macOS, and Catalyst. Namely the one that works. @balthisar's fork is the closest one that I found matching that requirement and "works" more-or-less "out of the box".

This is _after_ I made an attempt to [compile OpenSSL manually](https://cutecoder.org/programming/compile-open-ssl-apple-silicon/) for my mac project. When I moved on to iOS + Catalyst, things got a lot more difficult until I found [openssl-xcframeworks](https://github.com/balthisar/openssl-xcframeworks).

**Comment by keeshux** [comment]
> @keeshux Me? I was looking for an OpenSSL distribution that supports iOS, Simulator, macOS, and Catalyst. Namely the one that works. @balthisar's fork is the closest one that I found matching that requirement and "works" more-or-less "out of the box".
> 
> This is _after_ I made an attempt to [compile OpenSSL manually](https://cutecoder.org/programming/compile-open-ssl-apple-silicon/) for my mac project. When I moved on to iOS + Catalyst, things got a lot more difficult until I found [openssl-xcframeworks](https://github.com/balthisar/openssl-xcframeworks).

I see! My question is: what are your further requirements for going back to using this fork instead of the other one?

- XCFrameworks
- Carthage
- Apple Silicon
- ...

**Comment by balthisar** [comment]
I have no issue if you want to cherry pick my fork. I don't really have a lot time for maintaining it, and only now did I just realize that there are some PR's and issues open against it. :-(

**Comment by keeshux** [comment]
@balthisar you did a great and I hope you don't mind if I borrow parts here and there. :) This repo had gone unmaintained for a while so it somewhat made sense for forks to progress on their own. Now I'd like to catch up without disrupting too much. I understand you did a fair amount of refactoring.

**Comment by adib** [comment]
I went back primarily because there hasn’t been much activity in @balthisar’s fork, yours have more recent activities and there is also an Apple Silicon feature request. I’d figure to let you know by linking in my PR to the conversation for that feature request. Besides, I’m not that confident for the long-term maintenance of such fork.

As for further requirements, support for tvOS and watchOS simulators for ARM64 aren't there yet. At least it’s not in my PR. Support for those would be nice.

XCFrameworks is definitely Apple’s recommended way to distribute binary libraries. I feel it should be a priority over Carthage / Cocoapods / SPM. Static library support is important too — I use OpenSSL for license validation thus prefer static linking which should make it harder to patch/break.

Apple Silicon.. well, it’s about time and “something important” is going to be announced in November 10.
